### PR TITLE
Eliminate circular dependency between core & utils

### PR DESCRIPTION
**Pull request by ctrueden**
The class `javax.media.j3d.Font3D` of `j3d-core` imported classes from package `com.sun.j3d.utils.geometry`, which is part of `j3d-core-utils`. And the `j3d-core-utils` project imports many classes from `j3d-core`. This creates a circular dependency between artifacts.

This branch updates `java3d-core` to no longer depend on `java3d-utils` directly, but instead provide a `ServiceLoader`-based extensibility mechanism. That way, the `java3d-utils` component depends on `java3d-core`, but not vice versa.

See also:
* gouessej/java3d-utils#1 for the corresponding `GeometryService` implementation
* hharrison/java3d-core#17 for the original issue

### CODE REVIEW

**Comment by ctrueden** [comment]
I believe this is good to go (I removed the `@author` tag as requested), but I haven't tested it in a while. So some light testing on your end would be much appreciated!

**Comment by ctrueden** [comment]
I updated the [maven branch](https://github.com/gouessej/java3d-core/compare/pull/1/head...scijava:maven) on top of this work. I will rebase and file it as another PR as soon as this PR is merged.

**Comment by gouessej** [comment]
I'm going to test this this week and next week too. I'm quite confident.

**Comment by gouessej** [comment]
I had to modify the Ant script to set vecmath.lib to "../vecmath/target/vecmath-1.6.0-SNAPSHOT.jar". I'm impatient to build the whole engine with Maven :)

**Pull request merged**
